name: Goodbye World

# Events
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# Workflow / Jobs
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Goodbye
        run: echo "Goodbye World"
        shell: bash
      

